# Generated by Django 3.1.5 on 2021-02-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210215_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=1000)),
            ],
        ),
    ]
