# Generated by Django 3.1.5 on 2021-02-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_endpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoints',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
